'use strict'

/**
 * WASM engine loader — wraps the embedded vkv-neo wasm module (generated by
 * `npm run build:wasm` -> scripts/embed-wasm.mjs). Powered By Vexify.
 */

const { load } = require('../wasm/vkv-neo-wasm')
const { toBytes } = require('./bytes')

let exportsCache = null

function ex() {
  if (!exportsCache) exportsCache = load()
  return exportsCache
}

function mem() {
  return new Uint8Array(ex().memory.buffer)
}

const z = (n) => (typeof n === 'bigint' ? Number(n) : n)

function allocCopy(buf) {
  const p = ex().vkv_alloc(buf.length)
  if (buf.length) mem().set(buf, p)
  return p
}

class WasmEngine {
  get name() {
    return 'wasm'
  }

  set(key, value) {
    const kb = toBytes(key)
    const vb = toBytes(value)
    const kp = allocCopy(kb)
    const vp = allocCopy(vb)
    ex().vkv_put(kp, kb.length, vp, vb.length)
    ex().vkv_free(kp, kb.length)
    ex().vkv_free(vp, vb.length)
    return this
  }

  get(key) {
    const kb = toBytes(key)
    const kp = allocCopy(kb)
    // probe: i64::MIN -> missing; -(needed) -> value length needed
    let r = ex().vkv_get(kp, kb.length, ex().vkv_alloc(0), 0)
    if (r === -9223372036854775808n) {
      ex().vkv_free(kp, kb.length)
      return undefined
    }
    const cap = r < 0 ? -z(r) : z(r)
    const out = ex().vkv_alloc(cap)
    r = z(ex().vkv_get(kp, kb.length, out, cap))
    const v = Buffer.from(mem().slice(out, out + Math.max(r, 0)))
    ex().vkv_free(out, cap)
    ex().vkv_free(kp, kb.length)
    return v
  }

  has(key) {
    const kb = toBytes(key)
    const kp = allocCopy(kb)
    const r = z(ex().vkv_has(kp, kb.length))
    ex().vkv_free(kp, kb.length)
    return r === 1
  }

  del(key) {
    const kb = toBytes(key)
    const kp = allocCopy(kb)
    const r = z(ex().vkv_del(kp, kb.length))
    ex().vkv_free(kp, kb.length)
    return r === 1
  }

  get size() {
    return z(ex().vkv_len())
  }

  clear() {
    ex().vkv_clear()
  }

  putManyBytes(buf, count) {
    const p = allocCopy(buf)
    const n = z(ex().vkv_put_many(p, buf.length))
    ex().vkv_free(p, buf.length)
    return count === undefined || count === null ? n : Math.min(n, count)
  }

  getManyBytes(buf) {
    const p = allocCopy(buf)
    let needed = z(ex().vkv_get_many(p, buf.length, ex().vkv_alloc(0), 0))
    if (needed < 0) needed = -needed
    const out = ex().vkv_alloc(needed)
    const wrote = z(ex().vkv_get_many(p, buf.length, out, needed))
    const v = Buffer.from(mem().slice(out, out + wrote))
    ex().vkv_free(out, needed)
    ex().vkv_free(p, buf.length)
    return v
  }

  entries() {
    // probe: -(needed)
    let needed = z(ex().vkv_entries(ex().vkv_alloc(0), 0))
    if (needed < 0) needed = -needed
    const out = ex().vkv_alloc(needed)
    const wrote = z(ex().vkv_entries(out, needed))
    const v = Buffer.from(mem().slice(out, out + wrote))
    ex().vkv_free(out, needed)
    return v
  }

  version() {
    return z(ex().vkv_version())
  }
}

module.exports = { WasmEngine }